remote_theme: mmistakes/minimal-mistakes
title: "Sumit Pandey"
author:
  name: "Sumit Pandey"
  avatar: /assets/images/profile.png

description: "Portfolio, research, and code from a PhD researcher and AI developer"
plugins:
  - jekyll-include-cache
