remote_theme: mmistakes/minimal-mistakes
author:
  name: "Sumit Pandey"
  avatar: /assets/images/profile.jpg
  bio: "AI Scientist | PhD, University of Copenhagen | Ex-Harvard Med School"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:supa@di.ku.dk"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sumit-ai-ml"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sumit-pandey-ai"


description: "Portfolio, research, and code from a PhD researcher and AI developer"
plugins:
  - jekyll-include-cache
